### ISSUE TITLE
2 tracks playing at the same time

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1364]
Sometimes 2 tracks are playing at the same time.

The output stream and the web interface is playing 2 songs at the same time: 
![image](https://user-images.githubusercontent.com/19195485/134534074-d4500662-f8df-4f9b-a28b-6b6214cc00fd.png)

While checking the starts/ends timestamps I see that the 2 tracks are ending at the same time.
Please note the timestamps to check the provided logs below. 

Seem like the following is happening:
- Track 1 starts 
- Track 2 starts and track 1 starts again
- When track 2 ends, track 3 starts and track 1 stops

**To Reproduce**

I don't know how to reproduce yet.

**Expected behavior**

Track should play one after the other and not play twice.

**LibreTime version:**

main branch: dade43a1b1f71470945234c2079d6617ac681c0a

**Installation method:**

- OS: Debian 10
- Method:  ./install -fap
- Icecast is installed using ansible.

**Additional context**

[pypo.log](https://github.com/LibreTime/libretime/files/7218926/pypo.log)
[zendphp.log](https://github.com/LibreTime/libretime/files/7218927/zendphp.log)

Sidenote: We should really provide a libreitme-ctl CLI to manage/print status/prepare a gzip with logs for issue reporting.

**Comment by jooola** [comment]
I can provide a sql dump for testing/inspection

**Comment by paddatrapper** [comment]
How are those tracks scheduled? Are they a part of a smart block?

**Comment by jooola** [comment]
Yes, they are generated in a smartblock.

**Comment by jooola** [comment]
Show - Auto Playlist - Smartblock

**Comment by paddatrapper** [comment]
I suspect it is a race condition in the smart block generation then. What gives it away is that the times are listed as an issue there, so it is an issue in the creation of those schedule items before they are written into the database and not in the playout portion. Garbage in, garbage out

**Comment by jooola** [comment]
We might be facing 2 bugs here. I also have some songs playing at the same time, while they do not overlap in the schedule.

**Comment by jooola** [comment]
More weird things happening, previous and next track aren't even in the play queue, and the stream is a mix of 2 tracks
:
![](https://user-images.githubusercontent.com/19195485/135237937-180048da-a530-4214-a4fb-f14e23bd722e.jpg)

**Comment by jooola** [comment]
Found some weird data in the schedule table, posting it here for reference, but this a good lead to the source of the problem.

| id   | starts              | ends                | file_id | stream_id | clip_length  | fade_in  | fade_out | cue_in          | cue_out         | media_item_played | instance_id | playout_status | broadcasted | position |
| ---- | ------------------- | ------------------- | ------- | --------- | ------------ | -------- | -------- | --------------- | --------------- | ----------------- | ----------- | -------------- | ----------- | -------- |
| 5427 | 2021-09-29 15:01:59 | 2021-09-29 15:05:27 | 4013    |           | 00:03:27.864 | 00:00:00 | 00:00:00 | 00:00:00        | 00:03:27.8636   | true              | 152         | 1              | 1           | 29       |
| 5428 | 2021-09-29 15:05:27 | 2021-09-29 15:08:12 | 3980    |           | 00:02:45.902 | 00:00:00 | 00:00:00 | 00:00:00.202404 | 00:02:46.104467 | true              | 152         | 1              | 1           | 30       |
| 5378 | 2021-09-29 15:08:02 | 2021-09-29 15:12:48 | 5308    |           | 00:04:45.467 | 00:00:00 | 00:00:00 | 00:00:12.699206 | 00:04:58.165896 | false             | 153         | 0              | 0           | 39       |
| 5429 | 2021-09-29 15:08:12 | 2021-09-29 15:13:17 | 4474    |           | 00:05:05.006 | 00:00:00 | 00:00:00 | 00:00:00        | 00:05:05.005714 | true              | 152         | 1              | 1           | 31       |
| 5379 | 2021-09-29 15:12:48 | 2021-09-29 15:16:15 | 3895    |           | 00:03:26.982 | 00:00:00 | 00:00:00 | 00:00:00.503265 | 00:03:27.485283 | false             | 153         | 0              | 0           | 40       |

**Comment by Robbt** [comment]
So what we really need to do is figure out a way to replicate these kind of issues so that we can determine the actual source. 
I know there were some bugs in pypo that caused issues before we redid the API but now it seems like it maybe worse with the new python backend. I've been pretty absentee but until we can isolate the issues and reproduce them it will be very hard for us to troubleshoot. I know there has been a lot of work done on this and making the pypo logs less overwhelming so that we can better decipher them but I don't see us fixing this until we can figure out a way to reproduce these bugs in a test/development environment.

**Comment by jooola** [comment]
I am working on this and I think with the sql dump you would be able to reproduce this. I can share it if you like. 

From what I've been investigating so far, is that the new api v2 shedule api doesn't behave the way the old one used to.

When querying the shedule, we don't filter out schedule that aren't from the current show instance, and this result in multiple schedule from different show playing at the same time.

In my opinion, the complexity of the way we previously build the schedule cannot be easily implement in the django api if we stick to the REST pattern. And we maybe made a mistake by assuming we could simply mirror the DB with the REST API. But this doesn't help the issue at hand.

I'll try to filter out by how instance and wrap my head around this database data and compare how we process it compared to the old API.

**Comment by Robbt** [comment]
Building a easy way to compare the two APIs and iron out the differences is a good idea. We probably should have done this before we merged the API v2.

The next question is figuring out how to simplify the process, maybe this involves rewriting the pyop-liquidsoap pipeline to make things more logical and prevent some of these issues. There were obviously bugs before but they seem to have been a lot rarer.

**Comment by paddatrapper** [comment]
> When querying the shedule, we don't filter out schedule that aren't from the current show instance, and this result in multiple schedule from different show playing at the same time.

Fixed by #1361?

> In my opinion, the complexity of the way we previously build the schedule cannot be easily implement in the django api if we stick to the On-to-One DB <=> REST API pattern. And we maybe made a mistake by assuming we could simply mirror the DB with the REST API. But this doesn't help the issue at hand.

I think that the issue should be fixed on the input end, not the output. So the schedule in the DB should reflect 1:1 what will be played out at all times. Otherwise people building tools to integrate into LT (now/next, requests, etc) are going to have to have a lot of knowledge of LT internals to filter things out.

**Comment by jooola** [comment]
> Fixed by #1361?

Nope, in this issue we have multiple schedule at the same time because they belong to different show_instance (see data table above). And it seem we don't filter out the unplanned show instance.

> I think that the issue should be fixed on the input end, not the output. So the schedule in the DB should reflect 1:1 what will be played out at all times. Otherwise people building tools to integrate into LT (now/next, requests, etc) are going to have to have a lot of knowledge of LT internals to filter things out.

Ideally I agree with you when the use-case allows it, maybe it don't, but we will have to rework most of the legacy code to match our new database table schema, and this seems like a bad idea right now.

But I would actually prefer to have this global discussion in a another dedicated ticket and not hijack this issue.

**Comment by jooola** [comment]
This issue is maybe related to #916 and #381.

But in my case, the overlapping problem is happening really often, around 2 to 10 times a day.

**Comment by jooola** [comment]
I've been hunting down what `cc_schedule.playout_status` means, and I only found this little comment: https://github.com/LibreTime/libretime/blob/f809c3a8ffa282d02c652d1aec6f6eab37a59751/airtime_mvc/application/models/ShowBuilder.php#L122-L126

The old api was filtering out any items with playout_status > 0, so I am trying a small patch https://github.com/jooola/libretime/commit/3d9a327b964b9cde85dd3d020f25c958bde21f28 to see if this is related.

**Comment by jooola** [comment]
So the previous patch didn't fix the main issue we have, but was able to filter out some track that where missing/removed from the schedule.

I received an interesting input from one of our broadcaster, he said he played a lot with the linked shows, created a repeated linked show over the week, and moved some of its show instances to other time frames.
We noticed that the previously generated schedules for the initial time frame were still planned and valid for playout. While the show instance should have made the schedule invalid. This allowed for 2 playlist to play at the same time.

It is not yet very clear why this is happening, but I'll try to reproduce based on the steps I described above.

**Comment by jooola** [comment]
Found another similar bug:
- A new show starts, and the current playing track is faded out (I find the fade out really brutal I would suggest we smooth this a bit).
- The first song of the new show starts.
- After some time, it can be on the second track of the new show (the timestamps might be correlated to something), the previously fadeout song starts again, until it finishes and we listen 2 tracks at the same time.  

Here is the schedule table data:
|id|starts|ends|file_id|stream_id|clip_length|fade_in|fade_out|cue_in|cue_out|media_item_played|instance_id|playout_status|broadcasted|position|
|--|------|----|-------|---------|-----------|-------|--------|------|-------|-----------------|-----------|--------------|-----------|--------|
|7404|2021-10-03 14:18:13|2021-10-03 14:24:08|6991||00:05:55.109|00:00:00|00:00:00|00:00:00|00:05:55.108571|true|272|1|1|23|
|7405|2021-10-03 14:24:08|2021-10-03 14:28:47|1257||00:04:39.121|00:00:00|00:00:00|00:00:00.091723|00:04:39.212562|true|272|1|1|24|
|7406|2021-10-03 14:28:47|2021-10-03 14:32:29|6865||00:03:42.08|00:00:00|00:00:00|00:00:00|00:03:42.08|true|272|2|1|25|
|7408|2021-10-03 14:30:00|2021-10-03 14:30:11|29||00:00:11.5|00:00:00|00:00:00|00:00:00|00:00:11.4|true|277|1|1|0|
|7409|2021-10-03 14:30:11|2021-10-03 14:33:45|104||00:03:34.465|00:00:00|00:00:00|00:00:00.000023|00:03:34.465283|true|277|1|1|1|
|7407|2021-10-03 14:32:29|2021-10-03 14:32:41|5999||00:00:11.793|00:00:00|00:00:00|00:00:01.225688|00:00:13.019063|false|272|0|0|26|
|7410|2021-10-03 14:33:45|2021-10-03 14:37:28|111||00:03:42.208|00:00:00|00:00:00|00:00:01.119184|00:03:43.327029|true|277|1|1|2|
|7411|2021-10-03 14:37:28|2021-10-03 14:41:56|352||00:04:28.147|00:00:00|00:00:00|00:00:00|00:04:28.146937|true|277|1|1|3|

And here is our legal recording for this 5 minutes (the time frame is a bit weird because of the ffmpeg segment output):
[archive-20211003_162723.zip](https://github.com/LibreTime/libretime/files/7273612/archive-20211003_162723.zip)

**Comment by jooola** [comment]
Some interesting logs from liquidsoap:
```
2021/10/03 16:28:47 [server:3] New client: 127.0.0.1.
2021/10/03 16:28:47 [lang:3] vars.show_name
2021/10/03 16:28:47 [server:3] Client 127.0.0.1 disconnected.
2021/10/03 16:28:47 [cue_cut_7721:3] Cueing out...
2021/10/03 16:28:47 [s4:3] Finished with "/var/tmp/airtime/pypo/cache/scheduler/1257.flac".
2021/10/03 16:28:47 [amplify_7725:3] End of the current overriding.
2021/10/03 16:28:47 [dummy(dot)3:3] Source failed (no more tracks) stopping output...
2021/10/03 16:28:47 [dummy(dot)4:3] Source failed (no more tracks) stopping output...
2021/10/03 16:28:47 [schedule_noise_switch:3] Switch to map_metadata_7800 with forgetful transition.
2021/10/03 16:28:47 [lang:3] transition called...
2021/10/03 16:28:47 [decoder:3] Method "MAD" accepted "/var/tmp/airtime/pypo/cache/scheduler/6865.mp3".
2021/10/03 16:28:47 [s4:3] Prepared "/var/tmp/airtime/pypo/cache/scheduler/6865.mp3" (RID 0).
2021/10/03 16:28:47 [schedule_noise_switch:3] Switch to map_metadata_7793 with transition.
2021/10/03 16:28:47 [lang:3] transition called...
2021/10/03 16:28:47 [switch_7791:3] Switch to insert_metadata_7777.
2021/10/03 16:28:47 [amplify_7725:3] Overriding amplification: 0.299571.
2021/10/03 16:28:47 [lang:3] timeout --signal=KILL 45 pyponotify --media-id=7406 &
2021/10/03 16:28:47 [lang:3] Using stream_format 0
2021/10/03 16:28:47 [lang:3] Using stream_format 0
2021/10/03 16:28:47 [lang:3] Using stream_format 0
2021/10/03 16:30:00 [server:3] New client: 127.0.0.1.
2021/10/03 16:30:00 [lang:3] vars.show_name
2021/10/03 16:30:00 [server:3] Client 127.0.0.1 disconnected.
2021/10/03 16:30:00 [cue_cut_7721:3] Cueing out...
2021/10/03 16:30:00 [s4:3] Finished with "/var/tmp/airtime/pypo/cache/scheduler/6865.mp3".
2021/10/03 16:30:00 [amplify_7725:3] End of the current overriding.
2021/10/03 16:30:00 [dummy(dot)3:3] Source failed (no more tracks) stopping output...
2021/10/03 16:30:00 [dummy(dot)4:3] Source failed (no more tracks) stopping output...
2021/10/03 16:30:00 [decoder:3] Method "MAD" accepted "/var/tmp/airtime/pypo/cache/scheduler/29.mp3".
2021/10/03 16:30:00 [schedule_noise_switch:3] Switch to map_metadata_7800 with forgetful transition.
2021/10/03 16:30:00 [lang:3] transition called...
2021/10/03 16:30:00 [s4:3] Prepared "/var/tmp/airtime/pypo/cache/scheduler/29.mp3" (RID 1).
2021/10/03 16:30:00 [schedule_noise_switch:3] Switch to map_metadata_7793 with transition.
2021/10/03 16:30:00 [lang:3] transition called...
2021/10/03 16:30:00 [switch_7791:3] Switch to insert_metadata_7777.
2021/10/03 16:30:00 [amplify_7725:3] Overriding amplification: 2.423818.
2021/10/03 16:30:00 [lang:3] timeout --signal=KILL 45 pyponotify --media-id=7408 &
2021/10/03 16:30:00 [lang:3] Using stream_format 0
2021/10/03 16:30:00 [lang:3] Using stream_format 0
2021/10/03 16:30:00 [lang:3] Using stream_format 0
2021/10/03 16:30:11 [server:3] New client: 127.0.0.1.
2021/10/03 16:30:11 [lang:3] vars.show_name
2021/10/03 16:30:11 [server:3] Client 127.0.0.1 disconnected.
2021/10/03 16:30:11 [decoder:3] Method "MAD" accepted "/var/tmp/airtime/pypo/cache/scheduler/104.mp3".
2021/10/03 16:30:11 [cue_cut_7721:3] Cueing out...
2021/10/03 16:30:11 [s4:3] Finished with "/var/tmp/airtime/pypo/cache/scheduler/29.mp3".
2021/10/03 16:30:11 [amplify_7725:3] End of the current overriding.
2021/10/03 16:30:11 [s4:3] Prepared "/var/tmp/airtime/pypo/cache/scheduler/104.mp3" (RID 3).
2021/10/03 16:30:11 [cue_cut_7721:3] Cueing in...
2021/10/03 16:30:11 [amplify_7725:3] Overriding amplification: 0.550808.
2021/10/03 16:30:11 [lang:3] timeout --signal=KILL 45 pyponotify --media-id=7409 &
2021/10/03 16:30:11 [lang:3] Using stream_format 0
2021/10/03 16:30:11 [lang:3] Using stream_format 0
2021/10/03 16:30:11 [lang:3] Using stream_format 0
2021/10/03 16:31:02 [server:3] New client: 127.0.0.1.
2021/10/03 16:31:02 [lang:3] vars.show_name
2021/10/03 16:31:02 [server:3] Client 127.0.0.1 disconnected.
2021/10/03 16:31:02 [decoder:3] Method "MAD" accepted "/var/tmp/airtime/pypo/cache/scheduler/6865.mp3".
2021/10/03 16:31:02 [server:3] New client: 127.0.0.1.
2021/10/03 16:31:02 [lang:3] dynamic_source.get_id
2021/10/03 16:31:02 [server:3] Client 127.0.0.1 disconnected.
2021/10/03 16:31:02 [s3:3] Prepared "/var/tmp/airtime/pypo/cache/scheduler/6865.mp3" (RID 5).
2021/10/03 16:31:02 [cue_cut_7707:2] Ignoring cue-out point before cue-in. Note that cue-out should be given relative to the beginning of the file.
2021/10/03 16:31:02 [cue_cut_7707:3] Cueing in...
2021/10/03 16:31:02 [amplify_7711:3] Overriding amplification: 0.299571.
2021/10/03 16:31:02 [lang:3] timeout --signal=KILL 45 pyponotify --media-id=7406 &
2021/10/03 16:31:02 [lang:3] Using stream_format 0
2021/10/03 16:32:29 [s3:3] Finished with "/var/tmp/airtime/pypo/cache/scheduler/6865.mp3".
2021/10/03 16:32:29 [amplify_7711:3] End of the current overriding.
2021/10/03 16:32:29 [cross_7714:3] No next track ready yet.
```

I think I'll open a dedicated issue for this small bug and keep track of the linked show overlap here.

**Comment by tuktukvlad** [comment]
Hi
This definitely still happens on the latest version 4.0, I have encountered this several times in recent days, only restarting all services helps.

**Comment by tuktukvlad** [comment]
@jooola Hi
It happens every time after a few hours of playing and in this moment we can see that the station is not "on air"
Thanks
https://github.com/libretime/libretime/assets/22128719/d606dbc1-a2d4-4277-8b65-44a5500a208e
