### ISSUE TITLE
Debian 8.7 - Calender not Working

### ISSUE THREAD

**Issue by Lapotor** [LibreTime/libretime#145]
Hello Online the Calendar not working.
![LibreTime - Calendar](https://cloud.githubusercontent.com/assets/17144397/24768593/6c71773a-1b03-11e7-81a9-7a603176b9ff.png)

**Comment by hairmare** [comment]
This looks similar to #127. What browser are you on and does reloading the page with <kbd>Cmd+Shift+R</kbd> make a difference? Are there any errors on the developer tools console (<kbd>Cmd+Option+I</kbd> in Chrome)?

**Comment by Lapotor** [comment]
```
SyntaxError: expected expression, got ','[Weitere Informationen]  fullcalendar.js:405:50
unreachable code after return statement[Weitere Informationen]  moment.min.js:6:12432
TypeError: $(...).fullCalendar is not a function[Weitere Informationen]  schedule.js:23:132
getPreventDefault() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen defaultPrevented.  jquery-1.8.3.min.js:2:40351
```

**Comment by hairmare** [comment]
That might explain the issue, now I only need to figure out how to reproduce it so I can fix it 😟

**Comment by Robbt** [comment]
Did you install it via git or the tar ball ? I'm firing up a Debian 8.7 vbox to try.

**Comment by hairmare** [comment]
`fullCalendar is not a function` happens if the `#schedule_calendar` element does not get drawn so it's probably not the root cause.

**Comment by Lapotor** [comment]
I think it is the Git version but i don't know anymore

**Comment by hairmare** [comment]
It should show what you installed from in `/systemstatus`. The tarball should say 3.0.0-alpha, if it's from git it should tell what commit you where on when installing.

**Comment by Robbt** [comment]
I tried installing on a fresh Debian 8.7 system outside of vagrant from the git install and I didn't have this issue or an issue with liquidsoap so I'm not sure what is causing this.

**Comment by Lapotor** [comment]
@hairmare Where do i find the `/systemstatus` Folder ?
But i found `VERSION` with this in there: `8f372f5`

**Comment by Robbt** [comment]
Ok that shows you are running the version before we fixed the issue with liquidsoap. Can you run git pull from your libretime directory ? Then you will need to reinstall the airtime liquidsoap and the playout (although this may not be causing the calendar bug). 

To just install airtime-liquidsoap and play out again cd into the python-apps/pypo folder and run sudo python setup.py and this will install the new version which will hopefully get your liquidsoap working.

You could also try reinstalling all of the other files via sudo ./install -fiap and see if that fixes the calendar bug.

**Comment by hairmare** [comment]
`/systemstatus` is under "Settings" » "Status" in the main interface (and the version there shows the contents of `VERSION`).

**Comment by JohnnyC1951** [comment]
I had exactly this. I scrolled back up the install output and found that CURL was not installed and so lots of stuff did not get installed. I installed CURL, re-ran the install and it worked!

**Comment by Lapotor** [comment]
ok Now i reinstalled the Version from git from today: 
It say: `LibreTime Version`: `3`
And now the Calendar still not working, but by another guy it work on Chrome i tested it on Chrome, FireFox and Edge.
Here are the errors of the Console in Chrome:
```
Refused to execute script from 'http://libretime.simliveradio.net/locale/general-translation-table?3' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.
schedule:59 Uncaught ReferenceError: general_dict is not defined
    at schedule:59
(anonymous) @ schedule:59
fullcalendar.js?3:405 Uncaught SyntaxError: Unexpected token ,
schedule.js?3:23 Uncaught TypeError: $(...).fullCalendar is not a function
    at createFullCalendar (schedule.js?3:23)
    at preloadEventFeed (full-calendar-functions.js?3:32)
    at HTMLDocument.<anonymous> (full-calendar-functions.js?3:44)
    at l (jquery-1.8.3.min.js?3:2)
    at Object.fireWith [as resolveWith] (jquery-1.8.3.min.js?3:2)
    at Function.ready (jquery-1.8.3.min.js?3:2)
    at HTMLDocument.A (jquery-1.8.3.min.js?3:2)
```

And here the errors of from the Console in Firefox: 
```
Refused to execute script from 'http://libretime.simliveradio.net/locale/general-translation-table?3' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.
schedule:59 Uncaught ReferenceError: general_dict is not defined
    at schedule:59
(anonymous) @ schedule:59
fullcalendar.js?3:405 Uncaught SyntaxError: Unexpected token ,
schedule.js?3:23 Uncaught TypeError: $(...).fullCalendar is not a function
    at createFullCalendar (schedule.js?3:23)
    at preloadEventFeed (full-calendar-functions.js?3:32)
    at HTMLDocument.<anonymous> (full-calendar-functions.js?3:44)
    at l (jquery-1.8.3.min.js?3:2)
    at Object.fireWith [as resolveWith] (jquery-1.8.3.min.js?3:2)
    at Function.ready (jquery-1.8.3.min.js?3:2)
    at HTMLDocument.A (jquery-1.8.3.min.js?3:2)
```

I hope that helps you.

**Comment by Robbt** [comment]
This looks like a possible issue with the translation system. What language are you using LibreTime in ?

**Comment by Robbt** [comment]
Also found this **http://stackoverflow.com/questions/24528211/refused-to-execute-script-from-because-its-mime-type-application-json-is**

If your proxy server or container adds the following header when serving the .js file, it will force some browsers such as Chrome to perform strict checking of MIME types:

X-Content-Type-Options: nosniff

Remove this header to prevent Chrome performing the MIME check.

**Comment by hairmare** [comment]
Pretty sure this is a i18n issue `general_dict` should be defined  by a scripts that gets loaded early in the header. What language are you trying this with? Is there a difference between you station language and what you are choosing on the login screen? What are you choosing?

**Comment by hairmare** [comment]
Also, can you access http://localhost:8080/locale/general-translation-table directly? Does requesting it log anything?

**Comment by hairmare** [comment]
Sorry about all these questions that may look obvious. I think your station is set to german?

 The thing is the `application/json` wrong and should be `text/javascript `. I'm trying to figure out how the [call to `header()`](https://github.com/LibreTime/libretime/blob/e5295a0d583a12cf7e0491272790fef30bd7bb6a/airtime_mvc/application/controllers/LocaleController.php#L441) is not getting executed properly. I'm currently trying to reproduce this on Debian after having failed to do so with both CentOS and Ubuntu.

**Comment by hairmare** [comment]
Sure enough, while it isn't failing with a security warning in my Chrome. The general-translation-table URL is returning with a `Content-Type:application/json` header. I've yet to figure out why though.

**Comment by hairmare** [comment]
I just pushed #149 which should fix this. I think this has to do with us only testing on a localhost URL and chrome treating those slightly different in some security edge cases.

**Comment by Lapotor** [comment]
I preinstalled curl so i think that is it not.
And Station Language is German on login i tried English (default) and German both.

**Comment by Robbt** [comment]
Can you see if you are still getting the same message when using the debugger ? 
Also when you manually did the change did you modify the file inside of /usr/share/airtime/php/airtime_mvc vs. the install directory ?

**Comment by Lapotor** [comment]
Yeah the same.
I edit it in the `/usr/share/airtime` folder

**Comment by Robbt** [comment]
Can you check the console log to see if the same error is still cropping up regarding the MIME type ?

**Comment by hairmare** [comment]
Meh, I really hoped #149 would fix this 😞 I'll do some more testing with a non localhost domain and try figuring it out that way. I'm pretty sure that I'll be able to reproduce `Refused to execute script from 'http://libretime.simliveradio.net/locale/general-translation-table?3' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.` when I use a non localhost domain. I'm not sure why it would still happen after #149 though.

The `curl` change isn't part of the fix, it linked here due to https://github.com/LibreTime/libretime/issues/145#issuecomment-292744215

**Comment by Lapotor** [comment]
OK got the solution for me:
We use Cloudflare and we have restricted the Header so I changed that it not will be routed trough cloudflare but this is only tested via my phone.

**Comment by Lapotor** [comment]
Jep checked on PC now it works now thx for your time.
