### ISSUE TITLE
Debian 9 - Install Fail (Step 4 of 5)

### ISSUE THREAD

**Issue by amavarick** [LibreTime/libretime#360]
Step 4 of 5

Stays on this screen indefinitely:

![debian install freezing](https://user-images.githubusercontent.com/20918832/32916186-47ff0af2-cae9-11e7-933d-323f83cf24b3.png)

**Here are my exact install steps**:
```
apt install -y sudo nano locales
sudo apt-get update && sudo apt -y upgrade
sudo apt-get -y autoremove && sudo apt-get -y autoclean
#sudo reboot
sudo dpkg-reconfigure locales
sudo update-locale LANGUAGE="en_US.UTF-8"
sudo reboot
############# End Server Pre-Reqs #############################
#Disable IPv6 in /etc/hosts
#sudo sed -e 's/^::1/#::1/g' -i /etc/hosts
sudo sed -e 's/^fe/#fe/g' -i /etc/hosts
sudo sed -e 's/^ff/#ff/g' -i /etc/hosts
#Set SSHD to only listen to IPv4
sudo sed -i 's/^.*ListenAddress 0.0.0.0/ListenAddress 0.0.0.0/' /etc/ssh/sshd_config
sudo sed -i 's/^.*ListenAddress ::/#ListenAddress ::/' /etc/ssh/sshd_config
sudo sed -i 's/^.*Protocol 2/Protocol 2/' /etc/ssh/sshd_config
sudo sed -i 's/^.*ListenAddress ::/#ListenAddress ::/' /etc/ssh/sshd_config
sudo service sshd restart
#End Set SSHD to only listsen to IPv4
#Install automatic Updates
sudo apt -y install unattended-upgrades
#Install Libretime.org
#lsb_release -a
sudo apt -y install git && sudo git clone https://github.com/libretime/libretime.git
cd /root/libretime
./install -iap
```

Upon completing the steps above, I browse to the URL and walk through the setup wizard.  The setup wizard freezes on step 4/5.  After waiting hours to see if the screen changed, I did the following commands from CLI:
```
sudo service airtime-playout start
sudo service airtime-liquidsoap start
sudo service airtime_analyzer start
sudo service airtime-celery start
```
The configuration checklist appears to look good:
![configurationchecklist](https://user-images.githubusercontent.com/20918832/32916619-ade79518-caea-11e7-86e1-961d2a886062.png)

But after logging in, the settings are blank:
![blanksettings](https://user-images.githubusercontent.com/20918832/32916716-f77982f4-caea-11e7-9c5a-6dfe836e5b88.png)

No additional changes were made to the system other than those shown above.

**Comment by Robbt** [comment]
Hmm, I wonder if there is an error in the code I just pushed for the install process.
Can you look at /var/log/apache2/error.log and see if it has any errors in it, this and perhaps /var/log/airtime/zendphp.log (after the install)

**Comment by amavarick** [comment]
```
root@stream3:/var/log/apache2# cat error.log
[Thu Nov 16 19:37:30.551480 2017] [mpm_event:notice] [pid 1812:tid 140026260174016] AH00489: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Thu Nov 16 19:37:30.551574 2017] [core:notice] [pid 1812:tid 140026260174016] AH00094: Command line: '/usr/sbin/apache2'
[Thu Nov 16 19:37:36.808569 2017] [mpm_event:notice] [pid 1812:tid 140026260174016] AH00491: caught SIGTERM, shutting down
[Thu Nov 16 19:37:37.098521 2017] [mpm_prefork:notice] [pid 4521] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Thu Nov 16 19:37:37.098604 2017] [core:notice] [pid 4521] AH00094: Command line: '/usr/sbin/apache2'
[Thu Nov 16 19:37:37.352196 2017] [mpm_prefork:notice] [pid 4521] AH00169: caught SIGTERM, shutting down
[Thu Nov 16 19:37:37.460236 2017] [mpm_prefork:notice] [pid 4580] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Thu Nov 16 19:37:37.460292 2017] [core:notice] [pid 4580] AH00094: Command line: '/usr/sbin/apache2'
[Thu Nov 16 19:38:45.288512 2017] [mpm_prefork:notice] [pid 4580] AH00169: caught SIGTERM, shutting down
[Thu Nov 16 19:38:45.401436 2017] [mpm_prefork:notice] [pid 7337] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Thu Nov 16 19:38:45.401485 2017] [core:notice] [pid 7337] AH00094: Command line: '/usr/sbin/apache2'
```
```
root@stream3:/var/log/airtime# cat zendphp.log
2017-11-16T19:40:41-06:00 WARN (4): syrianalienation.com Your system does not have the en_CA.UTF-8 locale installed. Run: sudo locale-gen en_CA.UTF-8
2017-11-16T19:40:41-06:00 WARN (4): syrianalienation.com Your system does not have the en_CA.UTF-8 locale installed. Run: sudo locale-gen en_CA.UTF-8
2017-11-16T19:40:41-06:00 INFO (6): syrianalienation.com You must explicitly start the session with Zend_Session::start() when session options are set to strict.
2017-11-16T19:41:14-06:00 WARN (4): syrianalienation.com Your system does not have the en_CA.UTF-8 locale installed. Run: sudo locale-gen en_CA.UTF-8
2017-11-16T19:41:14-06:00 WARN (4): syrianalienation.com Your system does not have the en_CA.UTF-8 locale installed. Run: sudo locale-gen en_CA.UTF-8
2017-11-16T19:42:37-06:00 WARN (4): syrianalienation.com Your system does not have the en_CA.UTF-8 locale installed. Run: sudo locale-gen en_CA.UTF-8
2017-11-16T19:42:37-06:00 WARN (4): syrianalienation.com Your system does not have the en_CA.UTF-8 locale installed. Run: sudo locale-gen en_CA.UTF-8
2017-11-16T19:42:38-06:00 WARN (4): syrianalienation.com Your system does not have the en_CA.UTF-8 locale installed. Run: sudo locale-gen en_CA.UTF-8
2017-11-16T19:42:39-06:00 WARN (4): syrianalienation.com Your system does not have the en_CA.UTF-8 locale installed. Run: sudo locale-gen en_CA.UTF-8
```
```
root@stream3:/var/log/airtime# locale
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by Robbt** [comment]
Hmm, that error about `sudo locale-gen en_CA.UTF-8` is weird. I wonder if there is a dependency somewhere that we are unaware off. Have you tried running that command to see if it fixes the issue you are experiencing. I'm about to try and replicate it on a fresh debian vagrant install.

**Comment by Robbt** [comment]
Ok, I have duplicated this, something is going wrong in the installer. Let me figure out where the bug is and try to fix it ASAP.

**Comment by Robbt** [comment]
Ok, sorry about that. I have pushed a PR to revert one of the changes I did. Basically we are using hardcoded values and I tried to change this at one place but it didn't work and was causing an SIGTERM error that caused the database to not have the media dir initialized and hang. With this back it will work but we are still dependent upon default database values (at least during setup) and also require the manual modification of certain files afterwards.

**Comment by amavarick** [comment]
On the positive side, your changes worked, I can now get through the install and see the settings page!  I am now able to do a clean install and access the settings now.  However, there still is something that's expecting en_CA.UTF-8.  Running sudo locale-gen en_CA.UTF-8 and rebooting doesn't resolve the frequent/repeated error in zendphp.log.

```
root@stream3:/var/log/airtime# locale
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```
```
root@stream3:/var/log/airtime# tail -f zendphp.log
2017-11-17T15:10:44-06:00 INFO (6): stream3 Checking autoplaylist poll
2017-11-17T15:10:44-06:00 INFO (6): stream3 Checking to run Auto Playlist
2017-11-17T15:10:48-06:00 INFO (6): stream3 Notifying RabbitMQ to send message to pypo
2017-11-17T15:10:49-06:00 INFO (6): stream3 Registered Component: pypo@MYIPADDRESS
2017-11-17T15:10:49-06:00 INFO (6): stream3 Registered Component: show-recorder@MYIPADDRESS
2017-11-17T15:11:12-06:00 WARN (4): stream3 Your system does not have the en_CA.UTF-8 locale installed. Run: sudo locale-gen en_CA.UTF-8
2017-11-17T15:11:12-06:00 INFO (6): stream3 You must explicitly start the session with Zend_Session::start() when session options are set to strict.
2017-11-17T15:12:13-06:00 WARN (4): syrianalienation.com Your system does not have the en_CA.UTF-8 locale installed. Run: sudo locale-gen en_CA.UTF-8
2017-11-17T15:12:13-06:00 WARN (4): syrianalienation.com Your system does not have the en_CA.UTF-8 locale installed. Run: sudo locale-gen en_CA.UTF-8
2017-11-17T15:12:49-06:00 INFO (6): stream3 Checking autoplaylist poll
2017-11-17T15:12:49-06:00 INFO (6): stream3 Checking to run Auto Playlist
2017-11-17T15:13:26-06:00 WARN (4): syrianalienation.com Your system does not have the en_CA.UTF-8 locale installed. Run: sudo locale-gen en_CA.UTF-8
2017-11-17T15:13:26-06:00 WARN (4): syrianalienation.com Your system does not have the en_CA.UTF-8 locale installed. Run: sudo locale-gen en_CA.UTF-8
2017-11-17T15:13:43-06:00 WARN (4): syrianalienation.com Your system does not have the en_CA.UTF-8 locale installed. Run: sudo locale-gen en_CA.UTF-8
2017-11-17T15:13:43-06:00 WARN (4): syrianalienation.com Your system does not have the en_CA.UTF-8 locale installed. Run: sudo locale-gen en_CA.UTF-8
```

I ran the command sudo locale-gen en_CA.UTF-8 and rebooted
Still getting the following:
```
2017-11-17T15:43:12-06:00 WARN (4): stream3 Your system does not have the en_CA.UTF-8 locale installed. Run: sudo locale-gen en_CA.UTF-8
2017-11-17T15:43:13-06:00 WARN (4): stream3 Your system does not have the en_CA.UTF-8 locale installed. Run: sudo locale-gen en_CA.UTF-8
2017-11-17T15:43:15-06:00 WARN (4): stream3 Your system does not have the en_CA.UTF-8 locale installed. Run: sudo locale-gen en_CA.UTF-8
2017-11-17T15:43:15-06:00 WARN (4): stream3 Your system does not have the en_CA.UTF-8 locale installed. Run: sudo locale-gen en_CA.UTF-8
```

Do you want me to create a new issue for this?

**Comment by Robbt** [comment]
You could. I'm not sure it is a big issue but it appears that the default locale is en_CA (most likely because airtime development was based out of Toronto.
I found these lines in the default SQL
`airtime_mvc/build/sql/defaultdata.sql:INSERT INTO cc_pref("keystr", "valstr") VALUES('locale', 'en_CA');
airtime_mvc/build/sql/defaultdata.sql:INSERT INTO cc_pref("subjid", "keystr", "valstr") VALUES(1, 'user_locale', 'en_CA');
airtime_mvc/build/sql/defaultdata.sql:INSERT INTO cc_locale (locale_code, locale_lang) VALUES ('en_CA', 'English (Canada)');
`
