### ISSUE TITLE
Some MP3 files are "bad" and this results in dead air when scheduled

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#533]
So I have ran into this on my production server recently. I haven't dug deep enough into the cause but some files that were originally uploaded when the server was an Airtime instance (only noticed it with these so far) are not playing back when scheduled with Pypo and thus we have dead air for the duration of the track. 

These tracks appear to exist in the database still and on the filesystem (not as 0 byte files) but when I try to download them they are downloaded as 0 byte files.

I suspect that is possibly local file system corruption or something else occurring as the md5sum is different from the one in the database on this file. I suppose this is something that I'll need to diagnose but it would be ideal LibreTime could detect files that are bad before it schedules tries to play them to avoid dead air.

**Comment by hairmare** [comment]
This https://github.com/LibreTime/libretime/commit/fd6f3230ed9813b5c7f895f373d712abcddd41a3 might be a fix for your problem. I did it a while ago but was never able to reproduce what lead to the wrong files in the first place. I'll put it into a PR if you think it fixes the issue you're seeing.

**Comment by Robbt** [comment]
Yes! - that fixed it in terms of allowing the file to download. I'm not sure where the wrong files issue came in. The show in question appears to be shorter than our typical show. But the file on our website archive is the same length as the one that was imported into LibreTime.

I don't know where the md5 hash in the libretime database came from and why it is different from the md5 of the actual file. I suspect that this file may have been imported to our website in an incomplete form. The original mp3 was longer and it got chopped off during import and the last X minutes of the file were lost. 

The file was imported with airtime-media-import so it might of had a less stringent import process that took the ID3 description of the length vs. the actual length of the file and thus resulting in this issue. I uploaded it again with the web interface and it still detects the length incorrectly.

Do you think your PR fix the pypo playback issue ? 
I think there is also a bug in our import process if it detects a file as longer than it actually is.

**Comment by hairmare** [comment]
If I recall correctly my issue was also with files imported in media-monitor from legacy upstream, at least that's what 2017 me was most likely trying to say:

https://github.com/LibreTime/libretime/blob/fd6f3230ed9813b5c7f895f373d712abcddd41a3/airtime_mvc/application/common/FileIO.php#L30-L32

Pypo was actually working fine, but the download was getting chopped of when pypo tried to fetch the file from the API. I don't remember anything wrong about file hashes, maybe the files md5 hash was autocorrected by this nugget:

https://github.com/LibreTime/libretime/blob/fd6f3230ed9813b5c7f895f373d712abcddd41a3/python_apps/pypo/pypo/pypofile.py#L94-L125

Since I'm pretty sure that your issues should be fixed with sending a proper size I did https://github.com/LibreTime/libretime/pull/536

**Comment by Robbt** [comment]
Cool. Airtime-analyzer still reported the wrong length when I imported the file via the web interface, so although this fixes the issue with downloads and dead air it doesn't fix the issue of airtime-analyzer reading the length incorrectly for incomplete files.

**Comment by hairmare** [comment]
hmmpf... at least it got rid of the dead air issue.

**Comment by xabispacebiker** [comment]
So I think I am getting somewhere. If I access https://airtime.97irratia.info/rest/media/1311 through Safari I get the content, when I try from firefox I get the cassette screen with "Something went wrong!" message
